### ISSUE TITLE
improve add criterion workflow

### ISSUE THREAD

**Issue by alex-rind** [fhstp/highlighter-webextension#21]
- [x] clear textbox after "OK" 
- [x] add criterion on Enter key
- [x] immediately select checkbox for newly added item

**Comment by Ragitagha** [comment]
Added: Bug after click ok -> criteria is already added (it is not ^^ ) have to see how far I get!

**Comment by Ragitagha** [comment]
Main functionality at least added with https://github.com/fhstp/highlighter-webextension/commit/411853c0578dfd19e5481cf20475ad424d406173. Still open https://github.com/fhstp/highlighter-webextension/issues/21#issuecomment-417284632.
